### ISSUE TITLE
Paper and example to use censible

### ISSUE THREAD

**Issue by xavgit** [durrantlab/censible#1]
Hi,
there is a paper describing the workings of censible and 
some examples to use it in real problems to get a better
understanding of what can be done with it?
It is possible to have references to context explanation 
networks (CENs) that has been used to produce censible?

Thanks.

Saverio

**Comment by jacobdurrant** [comment]
Hi Saverio. Thanks for your interest in CENsible. We haven’t yet published a final version of the manuscript describing this work, but you can find a version here if you’d like a preview: https://www.biorxiv.org/content/10.1101/2023.10.18.562959v1

Take care,

Jacob

**Comment by xavgit** [comment]
Ok.
Thanks.

Saverio
